services:
  db:
    image: postgres:17
    container_name: chrono-db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - /srv/db:/var/lib/postgresql/data:rw
      - ../configs/postgresql.conf:/etc/postgresql.conf
    command: "-c config_file=/etc/postgresql.conf"
    healthcheck:
      test: "sh -c 'pg_isready -U $DB_USER'"
      interval: 1s
      retries: 5

  migrate:
    image: postgres:17-alpine
    container_name: chrono-migrate
    depends_on: 
      db:
        condition: service_healthy
    environment:
      POSTGRES_USER: ${DB_USER}
      PGPASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - ../migrations:/srv/migrations
      - ../scripts/migrate.sh:/srv/migrate.sh
    entrypoint: ["/srv/migrate.sh"]

  api:
    build:
      context: ../
      dockerfile: deployments/Dockerfile
    container_name: chrono-api
    expose:
      - "${APP_PORT}"
      - "${ADMIN_PORT}"
    depends_on:
      - migrate
    volumes:
      - ../:/srv
    command: sh -c "make run -C /srv"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.chrono-api.entrypoints=web"
      # - "traefik.http.routers.chrono-api.tls=true"
      # - "traefik.http.routers.chrono-api.tls.certresolver=cloudflare"
      # - "traefik.http.routers.chrono-api.entrypoints=websecure"
      - "traefik.http.routers.chrono-api.rule=Host(`${DOMAIN}`)"
      - "traefik.http.services.chrono-api.loadbalancer.server.port=${APP_PORT}"
      - "traefik.http.routers.chrono-api.middlewares=rateLimit@file,latencyCheck@file"

  traefik:
    image: traefik:v3.6
    container_name: traefik
    environment:
      CF_DNS_API_TOKEN: ${CF_DNS_API_TOKEN}
    command: "--certificatesresolvers.cloudflare.acme.email=${CF_EMAIL}"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - ../configs/traefik.yml:/etc/traefik/traefik.yaml:ro
      - ../configs/traefik_dynamic.yml:/etc/traefik/traefik_dynamic.yml:ro
      - ../certs:/var/traefik.certs:rw
      - /var/run/docker.sock:/var/run/docker.sock

  victoria:
    image: victoriametrics/victoria-metrics
    container_name: victoria
    expose:
      - "8428"
    volumes:
      - /srv/victoria:/storage
    command:
      - -storageDataPath=/storage
      - -retentionPeriod=90d
      - -loggerLevel=WARN
    healthcheck:
      test: ['CMD', 'wget', '--spider', '-q', 'http://127.0.0.1:8428/-/healthy']
      interval: 1s
      retries: 5

  vmagent:
    image: victoriametrics/vmagent
    container_name: vmagent
    depends_on:
      victoria:
        condition: service_healthy
    environment:
      ADMIN_PORT: ${ADMIN_PORT}
    expose:
      - "8429"
    volumes:
      - ../configs/vmagent.yml:/etc/vmagent/vmagent.yml
      - /srv/vmagent:/vmagentdata
    command:
      - -promscrape.config=/etc/vmagent/vmagent.yml
      - -remoteWrite.url=http://victoria:8428/api/v1/write
      - -loggerLevel=WARN

  victorialogs:
    image: victoriametrics/victoria-logs
    container_name: victorialogs
    depends_on:
      victoria:
        condition: service_healthy
    volumes:
      - /srv/victoria-logs:/data
    command:
      - -storageDataPath=/data
      - -retentionPeriod=14d
      - -defaultMsgValue=empty
      - -loggerLevel=WARN

  vector:
    image: timberio/vector:latest-alpine
    container_name: vector
    environment:
      VECTOR_LOG: warn
    depends_on:
      - victorialogs
    volumes:
      - ../configs/vector.yml:/etc/vector/vector.yaml:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro

  grafana:
    image: grafana/grafana-oss
    container_name: grafana
    environment:
      GF_PLUGINS_PREINSTALL: victoriametrics-logs-datasource
      GF_LOG_LEVEL: warn
      GF_SECURITY_ADMIN_USER: ${GRAFANA_USER}
      GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_PASSWORD}
    ports:
      - "3000:3000"
    volumes:
      - /srv/grafana:/var/lib/grafana:rw
      - ../configs/grafana.yml:/etc/grafana/provisioning/datasources/datasource.yaml:ro
    labels:
      - "traefik.enable=true"
