services:
  db:
    image: postgres:17
    container_name: chrono-db
    environment:
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASSWORD
      POSTGRES_DB: $DB_NAME
    volumes:
      - /srv/db:/var/lib/postgresql/data:rw
    ports:
      - "$DB_PORT:$DB_PORT"
    healthcheck:
      test: "pg_isready -U $DB_USER"
      interval: 1s
      retries: 5

  migrate:
    image: postgres:17-alpine
    container_name: chrono-migrate
    depends_on: 
      db:
        condition: service_healthy
    environment:
      POSTGRES_USER: $DB_USER
      PGPASSWORD: $DB_PASSWORD
      POSTGRES_DB: $DB_NAME
    volumes:
      - ../sql/migrations:/srv/migrations
      - ../scripts/migrate.sh:/srv/migrate.sh
    entrypoint: ["/srv/migrate.sh"]

  redis:
    image: redis:8.10-alpine
    container_name: chrono-redis
    environment:
      REDIS_PASSWORD: $REDIS_PASSWORD
    ports:
      - "$REDIS_PORT:$REDIS_PORT"
    healthcheck:
      test: "redis-cli --raw incr ping" 
      interval: 1s
      retries: 5

  api:
    build:
      context: ../
      dockerfile: deployments/Dockerfile
    container_name: chrono-api
    expose:
      - "$APP_PORT"
      - "$ADMIN_PORT"
    depends_on:
      migrate:
        condition: service_completed_successfully
      redis:
        condition: service_healthy
    volumes:
      - ../:/srv
    command: sh -c "make run -C /srv"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.chrono-api.entrypoints=web"
      # - "traefik.http.routers.chrono-api.tls=true"
      # - "traefik.http.routers.chrono-api.tls.certresolver=cloudflare"
      # - "traefik.http.routers.chrono-api.entrypoints=websecure"
      - "traefik.http.routers.chrono-api.rule=Host(`$DOMAIN`)"
      - "traefik.http.services.chrono-api.loadbalancer.server.port=$APP_PORT"
      - "traefik.http.routers.chrono-api.middlewares=rateLimit@file,latencyCheck@file"

  traefik:
    image: traefik:v3.6
    container_name: traefik
    environment:
      CF_DNS_API_TOKEN: $CF_DNS_API_TOKEN
    command: "--certificatesresolvers.cloudflare.acme.email=$CF_EMAIL"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - ../configs/traefik.yml:/etc/traefik/traefik.yaml:ro
      - ../configs/traefik_dynamic.yml:/etc/traefik/traefik_dynamic.yml:ro
      - ../certs:/var/traefik.certs:rw
      - /var/run/docker.sock:/var/run/docker.sock

  # Store metrics
  victoria-metrics:
    image: victoriametrics/victoria-metrics
    container_name: victoria-metrics
    expose:
      - "8428"
    volumes:
      - /srv/victoria-metrics:/storage
    command:
      - -storageDataPath=/storage
      - -retentionPeriod=90d
      - -loggerLevel=WARN
    healthcheck:
      test: ['CMD', 'wget', '--spider', '-q', 'http://127.0.0.1:8428/-/healthy']
      interval: 1s
      retries: 5

  # Collect metrics
  vmagent:
    image: victoriametrics/vmagent
    container_name: vmagent
    depends_on:
      victoria-metrics:
        condition: service_healthy
    environment:
      ADMIN_PORT: $ADMIN_PORT
    expose:
      - "8429"
    volumes:
      - ../configs/vmagent.yml:/etc/vmagent/vmagent.yml
      - /srv/vmagent:/vmagentdata
    command:
      - -promscrape.config=/etc/vmagent/vmagent.yml
      - -remoteWrite.url=http://victoria-metrics:8428/api/v1/write
      - -loggerLevel=WARN

  # Store logs
  victoria-logs:
    image: victoriametrics/victoria-logs
    container_name: victoria-logs
    depends_on:
      victoria-metrics:
        condition: service_healthy
    volumes:
      - /srv/victoria-logs:/data
    command:
      - -storageDataPath=/data
      - -retentionPeriod=14d
      - -defaultMsgValue=empty
      - -loggerLevel=WARN

  # Collect logs
  vector:
    image: timberio/vector:latest-alpine
    container_name: vector
    environment:
      VECTOR_LOG: warn
    depends_on:
      - victoria-logs
    volumes:
      - ../configs/vector.yml:/etc/vector/vector.yaml:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro

  # Visualize logs & metrics
  grafana:
    image: grafana/grafana-oss
    container_name: grafana
    environment:
      GF_PLUGINS_PREINSTALL: victoriametrics-logs-datasource
      GF_LOG_LEVEL: warn
      GF_SECURITY_ADMIN_USER: $GRAFANA_USER
      GF_SECURITY_ADMIN_PASSWORD: $GRAFANA_PASSWORD
    ports:
      - "3000:3000"
    volumes:
      - /srv/grafana:/var/lib/grafana:rw
      - ../configs/grafana.yml:/etc/grafana/provisioning/datasources/datasource.yaml:ro
    labels:
      - "traefik.enable=true"
    depends_on:
      victoria-metrics:
        condition: service_healthy
