stages:
  - lint
  - build
  - test

lint:
  stage: lint
  image: alpine
  before_script:
    - apk add --no-cache make go curl
    - curl -sSfL https://golangci-lint.run/install.sh | sh -s -- -b /usr/bin
  script:
    - make lint

build:
  stage: build
  image: alpine
  before_script:
    - apk add --no-cache make go
  script:
    - make build

test:
  stage: test
  image: docker
  services:
  - docker:dind
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""
  before_script:
    - apk add --no-cache make docker-compose
  script:
    - make test-up
