services:
  db:
    image: postgres:17
    container_name: chrono-db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - /srv/db:/var/lib/postgresql/data:rw
      - ./configs/postgresql.conf:/etc/postgresql.conf
    command: "-c config_file=/etc/postgresql.conf"
    healthcheck:
      test: "sh -c 'pg_isready -U $DB_USER'"
      interval: 1s
      retries: 5

  migrate:
    image: postgres:17-alpine
    container_name: chrono-migrate
    depends_on: 
      db:
        condition: service_healthy
    environment:
      POSTGRES_USER: ${DB_USER}
      PGPASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - ./migrations:/srv/migrations
      - ./scripts/migrate.sh:/srv/migrate.sh
    entrypoint: ["/srv/migrate.sh"]

  api:
    build:
      dockerfile: Dockerfile
    container_name: chrono-api
    expose:
      - "${APP_PORT}"
    ports:
      - "9010:9010"
    depends_on:
      - migrate
    volumes:
      - .:/srv
    command: sh -c "make run -C /srv"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.chrono-api.entrypoints=web"
      # - "traefik.http.routers.chrono-api.tls=true"
      # - "traefik.http.routers.chrono-api.tls.certresolver=cloudflare"
      # - "traefik.http.routers.chrono-api.entrypoints=websecure"
      - "traefik.http.routers.chrono-api.rule=Host(`${DOMAIN}`)"
      - "traefik.http.services.chrono-api.loadbalancer.server.port=${APP_PORT}"
      - "traefik.http.routers.chrono-api.middlewares=rateLimit@file,latencyCheck@file"

  traefik:
    image: traefik:v3.6
    container_name: traefik
    environment:
      CF_DNS_API_TOKEN: ${CF_DNS_API_TOKEN}
    command: "--certificatesresolvers.cloudflare.acme.email=${CF_EMAIL}"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - ./configs/traefik.yml:/etc/traefik/traefik.yaml:ro
      - ./configs/traefik_dynamic.yml:/etc/traefik/traefik_dynamic.yml:ro
      - ./certs:/var/traefik.certs:rw
      - /var/run/docker.sock:/var/run/docker.sock

  prometheus:
    container_name: prometheus
    image: prom/prometheus
    command: 
    - "--log.level=warn"
    - "--config.file=/etc/prometheus/prometheus.yml"
    volumes:
      - ./configs/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"

  loki: 
    image: grafana/loki
    container_name: loki
    command: "-config.file=/etc/loki/config.yaml"
    ports:
      - "3100:3100"
    volumes:
      - /srv/loki:/srv/loki:rw
      - ./configs/loki.yml:/etc/loki/config.yaml:ro

  alloy:
    image: grafana/alloy
    container_name: alloy
    volumes:
      - ./configs/alloy.conf:/etc/alloy/config.alloy
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      LOKI_HOST: loki:3100
    depends_on:
      - loki
    command:
      - "run"
      - "/etc/alloy/config.alloy"
      - "--storage.path=/var/lib/alloy/data"
      - "--server.http.listen-addr=0.0.0.0:3200"
      - "--stability.level=experimental"
    ports:
      - "3200:3200"

  grafana:
    image: grafana/grafana-enterprise
    container_name: grafana
    environment:
      GF_LOG_LEVEL: warn
      GF_SECURITY_ADMIN_USER: ${GRAFANA_USER}
      GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_PASSWORD}
    ports:
      - "3000:3000"
    volumes:
      - /srv/grafana:/var/lib/grafana:rw
      - ./configs/grafana.yml:/etc/grafana/provisioning/datasources/datasource.yaml:ro
    labels:
      - "traefik.enable=true"
