services:
  db:
    image: postgres:17-alpine
    container_name: chrono-db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - /srv/db:/var/lib/postgresql/data:rw
      - ./configs/postgresql.conf:/var/lib/postgresql/data/postgresql.conf
    healthcheck:
      test: "sh -c 'pg_isready -U $DB_USER'"
      interval: 1s
      retries: 5

  migrate:
    image: postgres:17-alpine
    container_name: chrono-migrate
    depends_on: 
      db:
        condition: service_healthy
    environment:
      POSTGRES_USER: ${DB_USER}
      PGPASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - ./migrations:/srv/migrations
      - ./scripts/migrate.sh:/srv/migrate.sh
    entrypoint: ["/srv/migrate.sh"]

  api:
    build:
      dockerfile: Dockerfile
    container_name: chrono-api
    expose:
      - "${APP_PORT}"
    ports:
      - "9010:9010"
    depends_on:
      - migrate
    volumes:
      - .:/srv
    command: sh -c "make run -C /srv"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.chrono-api.rule=Host(`${DOMAIN}`)"
      - "traefik.http.services.chrono-api.loadbalancer.server.port=${APP_PORT}"
      - "traefik.http.routers.chrono-api.middlewares=rateLimit@file,latencyCheck@file"
      - "logging=promtail"

  traefik:
    image: traefik:v3.6
    container_name: traefik
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - ./configs/traefik.yml:/etc/traefik/traefik.yaml:ro
      - ./configs/traefik_dynamic.yml:/etc/traefik/traefik_dynamic.yml:ro
      - /var/run/docker.sock:/var/run/docker.sock

  prometheus:
    container_name: prometheus
    image: prom/prometheus
    volumes:
      - ./configs/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"

  loki: 
    image: grafana/loki
    container_name: loki
    command: "-config.file=/etc/loki/config.yaml"
    ports:
      - "3100:3100"
    volumes:
      - /srv/loki:/srv/loki:rw
      - ./configs/loki.yml:/etc/loki/config.yaml:ro

  promtail:
    image: grafana/promtail
    container_name: promtail
    volumes:
      - ./configs/promtail.yml:/etc/promtail/docker-config.yaml:ro
      - /var/lib/docker/containers:/var/lib/docker/containers
      - /var/run/docker.sock:/var/run/docker.sock
    command: -config.file=/etc/promtail/docker-config.yaml
    
  grafana:
    image: grafana/grafana-enterprise
    container_name: grafana
    environment:
      GF_LOG_LEVEL: warn
      GF_SECURITY_ADMIN_USER: ${GRAFANA_USER}
      GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_PASSWORD}
    ports:
      - "3000:3000"
    volumes:
      - /srv/grafana:/var/lib/grafana:rw
      - ./configs/grafana.yml:/etc/grafana/provisioning/datasources/datasource.yaml:ro
    labels:
      - "traefik.enable=true"
