// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: copyfrom.go

package query

import (
	"context"
)

// iteratorForCreateLeaderboardUsers implements pgx.CopyFromSource.
type iteratorForCreateLeaderboardUsers struct {
	rows                 []CreateLeaderboardUsersParams
	skippedFirstNextCall bool
}

func (r *iteratorForCreateLeaderboardUsers) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForCreateLeaderboardUsers) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].SnapshotID,
		r.rows[0].UserID,
		r.rows[0].Rank,
	}, nil
}

func (r iteratorForCreateLeaderboardUsers) Err() error {
	return nil
}

func (q *Queries) CreateLeaderboardUsers(ctx context.Context, arg []CreateLeaderboardUsersParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"leaderboard_users"}, []string{"snapshot_id", "user_id", "rank"}, &iteratorForCreateLeaderboardUsers{rows: arg})
}
