// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: forms.sql

package query

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createBugReport = `-- name: CreateBugReport :exec
INSERT INTO bug_reports (name, email, title, description, steps, environment, additional)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type CreateBugReportParams struct {
	Name        pgtype.Text
	Email       pgtype.Text
	Title       string
	Description string
	Steps       pgtype.Text
	Environment pgtype.Text
	Additional  pgtype.Text
}

func (q *Queries) CreateBugReport(ctx context.Context, arg CreateBugReportParams) error {
	_, err := q.db.Exec(ctx, createBugReport,
		arg.Name,
		arg.Email,
		arg.Title,
		arg.Description,
		arg.Steps,
		arg.Environment,
		arg.Additional,
	)
	return err
}

const createFeatureRequest = `-- name: CreateFeatureRequest :exec
INSERT INTO feature_requests (name, email, title, problem, feature, priority)
VALUES ($1, $2, $3, $4, $5, $6)
`

type CreateFeatureRequestParams struct {
	Name     pgtype.Text
	Email    pgtype.Text
	Title    string
	Problem  string
	Feature  string
	Priority string
}

func (q *Queries) CreateFeatureRequest(ctx context.Context, arg CreateFeatureRequestParams) error {
	_, err := q.db.Exec(ctx, createFeatureRequest,
		arg.Name,
		arg.Email,
		arg.Title,
		arg.Problem,
		arg.Feature,
		arg.Priority,
	)
	return err
}
