// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: friend.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const acceptFriendRequest = `-- name: AcceptFriendRequest :exec
UPDATE friends
SET is_accepted = true
WHERE sender_id = $1 AND recipient_id = $2
`

type AcceptFriendRequestParams struct {
	SenderID    uuid.UUID
	RecipientID uuid.UUID
}

func (q *Queries) AcceptFriendRequest(ctx context.Context, arg AcceptFriendRequestParams) error {
	_, err := q.db.Exec(ctx, acceptFriendRequest, arg.SenderID, arg.RecipientID)
	return err
}

const createFriendRequest = `-- name: CreateFriendRequest :exec
INSERT INTO friends(sender_id, recipient_id)
VALUES($1, $2)
`

type CreateFriendRequestParams struct {
	SenderID    uuid.UUID
	RecipientID uuid.UUID
}

func (q *Queries) CreateFriendRequest(ctx context.Context, arg CreateFriendRequestParams) error {
	_, err := q.db.Exec(ctx, createFriendRequest, arg.SenderID, arg.RecipientID)
	return err
}

const deleteFriend = `-- name: DeleteFriend :exec
DELETE FROM friends
WHERE
    sender_id = $1 AND recipient_id = $2
    OR sender_id = $2 AND recipient_id = $1
`

type DeleteFriendParams struct {
	SenderID    uuid.UUID
	RecipientID uuid.UUID
}

func (q *Queries) DeleteFriend(ctx context.Context, arg DeleteFriendParams) error {
	_, err := q.db.Exec(ctx, deleteFriend, arg.SenderID, arg.RecipientID)
	return err
}

const getFriendRequests = `-- name: GetFriendRequests :many
SELECT id, sender_id, recipient_id, is_accepted FROM friends
WHERE recipient_id = $1
`

func (q *Queries) GetFriendRequests(ctx context.Context, recipientID uuid.UUID) ([]Friend, error) {
	rows, err := q.db.Query(ctx, getFriendRequests, recipientID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Friend{}
	for rows.Next() {
		var i Friend
		if err := rows.Scan(
			&i.ID,
			&i.SenderID,
			&i.RecipientID,
			&i.IsAccepted,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSentFriendRequests = `-- name: GetSentFriendRequests :many
SELECT id, sender_id, recipient_id, is_accepted FROM friends
WHERE sender_id = $1
`

func (q *Queries) GetSentFriendRequests(ctx context.Context, senderID uuid.UUID) ([]Friend, error) {
	rows, err := q.db.Query(ctx, getSentFriendRequests, senderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Friend{}
	for rows.Next() {
		var i Friend
		if err := rows.Scan(
			&i.ID,
			&i.SenderID,
			&i.RecipientID,
			&i.IsAccepted,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTopFriends = `-- name: GetTopFriends :many
SELECT users.id, users.email, users.username, users.password, users.total_time_tracked_seconds, users.today_time_tracked_seconds, users.city, users.created_at, users.updated_at FROM friends
JOIN users ON users.id = friends.recipient_id
WHERE 
    friends.is_accepted = TRUE
    AND users.id = $1
    AND users.total_time_tracked_seconds < $2
ORDER BY users.total_time_tracked_seconds DESC
LIMIT $3
`

type GetTopFriendsParams struct {
	ID                      uuid.UUID
	TotalTimeTrackedSeconds int32
	Limit                   int32
}

func (q *Queries) GetTopFriends(ctx context.Context, arg GetTopFriendsParams) ([]User, error) {
	rows, err := q.db.Query(ctx, getTopFriends, arg.ID, arg.TotalTimeTrackedSeconds, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Username,
			&i.Password,
			&i.TotalTimeTrackedSeconds,
			&i.TodayTimeTrackedSeconds,
			&i.City,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
