// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: friend.sql

package query

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const acceptFriendRequest = `-- name: AcceptFriendRequest :exec
UPDATE friends
SET 
    is_accepted = true,
    updated_at = now()
FROM users WHERE
    users.id = friends.sender_id
    AND users.username = $1 AND recipient_id = $2
`

type AcceptFriendRequestParams struct {
	Username    string
	RecipientID uuid.UUID
}

func (q *Queries) AcceptFriendRequest(ctx context.Context, arg AcceptFriendRequestParams) error {
	_, err := q.db.Exec(ctx, acceptFriendRequest, arg.Username, arg.RecipientID)
	return err
}

const createFriendRequest = `-- name: CreateFriendRequest :exec
INSERT INTO friends(sender_id, recipient_id)
SELECT $1, id
FROM users
WHERE username = $2
`

type CreateFriendRequestParams struct {
	SenderID uuid.UUID
	Username string
}

func (q *Queries) CreateFriendRequest(ctx context.Context, arg CreateFriendRequestParams) error {
	_, err := q.db.Exec(ctx, createFriendRequest, arg.SenderID, arg.Username)
	return err
}

const deleteFriend = `-- name: DeleteFriend :exec
DELETE FROM friends
USING users
WHERE 
    users.username = $2 AND
    ((sender_id = $1 AND recipient_id = $2)
    OR (sender_id = $2 AND recipient_id = $1))
`

type DeleteFriendParams struct {
	SenderID uuid.UUID
	Username string
}

func (q *Queries) DeleteFriend(ctx context.Context, arg DeleteFriendParams) error {
	_, err := q.db.Exec(ctx, deleteFriend, arg.SenderID, arg.Username)
	return err
}

const getFriendRequests = `-- name: GetFriendRequests :many
SELECT friends.created_at, sender.username FROM friends
JOIN users AS sender ON users.id = friends.sender_id
JOIN users AS recipient ON users.id = friends.recipient_id
WHERE 
    recipient.id = $1
    AND friends.is_accepted = FALSE
`

type GetFriendRequestsRow struct {
	CreatedAt pgtype.Timestamptz
	Username  string
}

func (q *Queries) GetFriendRequests(ctx context.Context, id uuid.UUID) ([]GetFriendRequestsRow, error) {
	rows, err := q.db.Query(ctx, getFriendRequests, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetFriendRequestsRow{}
	for rows.Next() {
		var i GetFriendRequestsRow
		if err := rows.Scan(&i.CreatedAt, &i.Username); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFriendStatus = `-- name: GetFriendStatus :one
SELECT friends.is_accepted FROM friends
JOIN users ON users.id = friends.recipient_id
WHERE users.username = $1
`

func (q *Queries) GetFriendStatus(ctx context.Context, username string) (bool, error) {
	row := q.db.QueryRow(ctx, getFriendStatus, username)
	var is_accepted bool
	err := row.Scan(&is_accepted)
	return is_accepted, err
}

const getTopFriends = `-- name: GetTopFriends :many
SELECT users.id, users.email, users.username, users.password, users.total_time_tracked_seconds, users.today_time_tracked_seconds, users.country, users.hide_country, users.hide_user, users.last_seen_at, users.created_at, users.updated_at FROM friends
JOIN users ON 
    users.id = friends.recipient_id
    OR users.id = friends.sender_id
WHERE 
    users.id = $1
    AND friends.is_accepted = TRUE
    AND users.total_time_tracked_seconds < $2
    AND username ILIKE $4 || '%'
    AND users.hide_user = FALSE
ORDER BY users.total_time_tracked_seconds DESC
LIMIT $3
`

type GetTopFriendsParams struct {
	ID                      uuid.UUID
	TotalTimeTrackedSeconds int32
	Limit                   int32
	MatchName               pgtype.Text
}

func (q *Queries) GetTopFriends(ctx context.Context, arg GetTopFriendsParams) ([]User, error) {
	rows, err := q.db.Query(ctx, getTopFriends,
		arg.ID,
		arg.TotalTimeTrackedSeconds,
		arg.Limit,
		arg.MatchName,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Username,
			&i.Password,
			&i.TotalTimeTrackedSeconds,
			&i.TodayTimeTrackedSeconds,
			&i.Country,
			&i.HideCountry,
			&i.HideUser,
			&i.LastSeenAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
