// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: leaderboard.sql

package query

import (
	"context"

	"uuid"
)

const createLeaderboardSnapshot = `-- name: CreateLeaderboardSnapshot :one
INSERT INTO leaderboard_snapshots
DEFAULT VALUES
RETURNING id
`

func (q *Queries) CreateLeaderboardSnapshot(ctx context.Context) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createLeaderboardSnapshot)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

type CreateLeaderboardUsersParams struct {
	SnapshotID uuid.UUID
	UserID     uuid.UUID
	Rank       int32
}

const getLastLeaderboardUsers = `-- name: GetLastLeaderboardUsers :many
SELECT id, snapshot_id, user_id, rank FROM leaderboard_users
WHERE snapshot_id = (
    SELECT id
    FROM leaderboard_snapshots
    ORDER BY created_at DESC
    LIMIT 1
)
`

func (q *Queries) GetLastLeaderboardUsers(ctx context.Context) ([]LeaderboardUser, error) {
	rows, err := q.db.Query(ctx, getLastLeaderboardUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LeaderboardUser{}
	for rows.Next() {
		var i LeaderboardUser
		if err := rows.Scan(
			&i.ID,
			&i.SnapshotID,
			&i.UserID,
			&i.Rank,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
