// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: leaderboard.sql

package query

import (
	"context"

	"github.com/google/uuid"
)

const createLeaderboardSnapshot = `-- name: CreateLeaderboardSnapshot :one
INSERT INTO leaderboard_snapshots
DEFAULT VALUES
RETURNING id
`

func (q *Queries) CreateLeaderboardSnapshot(ctx context.Context) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createLeaderboardSnapshot)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const createLeaderboardUser = `-- name: CreateLeaderboardUser :exec
INSERT INTO leaderboard_users(snapshot_id, user_id, rank, rank_change)
VALUES($1, $2, $3, $4)
`

type CreateLeaderboardUserParams struct {
	SnapshotID uuid.UUID
	UserID     uuid.UUID
	Rank       int32
	RankChange int32
}

func (q *Queries) CreateLeaderboardUser(ctx context.Context, arg CreateLeaderboardUserParams) error {
	_, err := q.db.Exec(ctx, createLeaderboardUser,
		arg.SnapshotID,
		arg.UserID,
		arg.Rank,
		arg.RankChange,
	)
	return err
}

const getLastLeaderboardUsers = `-- name: GetLastLeaderboardUsers :many
SELECT id, snapshot_id, user_id, rank, rank_change, created_at, updated_at FROM leaderboard_users
WHERE snapshot_id = (
    SELECT id
    FROM leaderboard_snapshots
    ORDER BY created_at DESC
    LIMIT 1
)
`

func (q *Queries) GetLastLeaderboardUsers(ctx context.Context) ([]LeaderboardUser, error) {
	rows, err := q.db.Query(ctx, getLastLeaderboardUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LeaderboardUser{}
	for rows.Next() {
		var i LeaderboardUser
		if err := rows.Scan(
			&i.ID,
			&i.SnapshotID,
			&i.UserID,
			&i.Rank,
			&i.RankChange,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
