// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: location.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const setLocationPrivacy = `-- name: SetLocationPrivacy :exec
UPDATE users
SET hide_country = $2, updated_at = now()
WHERE id = $1
`

type SetLocationPrivacyParams struct {
	ID          uuid.UUID
	HideCountry bool
}

func (q *Queries) SetLocationPrivacy(ctx context.Context, arg SetLocationPrivacyParams) error {
	_, err := q.db.Exec(ctx, setLocationPrivacy, arg.ID, arg.HideCountry)
	return err
}
