// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package query

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type BugReport struct {
	ID          int64
	Name        pgtype.Text
	Email       pgtype.Text
	Title       string
	Description string
	Steps       pgtype.Text
	Environment pgtype.Text
	Additional  pgtype.Text
	CreatedAt   time.Time
}

type FeatureRequest struct {
	ID        int64
	Name      pgtype.Text
	Email     pgtype.Text
	Title     string
	Problem   string
	Feature   string
	Priority  string
	CreatedAt time.Time
}

type Friend struct {
	ID          uuid.UUID
	SenderID    uuid.UUID
	RecipientID uuid.UUID
	IsAccepted  bool
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type OtpToken struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	Hash      string
	Expiry    time.Time
	CreatedAt pgtype.Timestamptz
}

type Session struct {
	ID                      uuid.UUID
	OwnerID                 uuid.UUID
	Name                    string
	MaxParticipants         pgtype.Int4
	Password                pgtype.Text
	ExpiresAt               pgtype.Timestamptz
	Topic                   pgtype.Text
	TotalTimeTrackedSeconds int32
	IsActive                bool
	CreatedAt               time.Time
	UpdatedAt               time.Time
}

type SessionParticipant struct {
	ID                      uuid.UUID
	UserID                  uuid.UUID
	SessionID               uuid.UUID
	TotalTimeTrackedSeconds int32
	TodayTimeTrackedSeconds int32
}

type SessionToken struct {
	ID         uuid.UUID
	UserID     uuid.UUID
	Hash       string
	Expiry     time.Time
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
	LastUsedAt pgtype.Timestamptz
}

type Topic struct {
	ID                      uuid.UUID
	Name                    string
	Streak                  int32
	TotalTimeTrackedSeconds int32
	TodayTimeTrackedSeconds int32
	OwnerID                 uuid.UUID
	CreatedAt               time.Time
	UpdatedAt               time.Time
}

type TopicEvent struct {
	ID                 uuid.UUID
	UserID             uuid.UUID
	TopicID            uuid.UUID
	TimeTrackedSeconds int32
	CreatedAt          time.Time
}

type User struct {
	ID                      uuid.UUID
	Email                   string
	Username                string
	Password                string
	TotalTimeTrackedSeconds int32
	TodayTimeTrackedSeconds int32
	Country                 pgtype.Text
	HideCountry             bool
	HideUser                bool
	LastSeenAt              time.Time
	CreatedAt               pgtype.Timestamptz
	UpdatedAt               pgtype.Timestamptz
}
