// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Session struct {
	ID             int32              `db:"id"`
	Name           string             `db:"name"`
	Password       pgtype.Text        `db:"password"`
	OwnerID        int32              `db:"owner_id"`
	ParticipantIds []int32            `db:"participant_ids"`
	Expiry         pgtype.Timestamptz `db:"expiry"`
	CreatedAt      pgtype.Timestamptz `db:"created_at"`
	UpdatedAt      pgtype.Timestamptz `db:"updated_at"`
}

type Topic struct {
	ID                 int32              `db:"id"`
	Name               string             `db:"name"`
	TimeTrackedSeconds int32              `db:"time_tracked_seconds"`
	CreatedByUserid    int32              `db:"created_by_userid"`
	CreatedAt          pgtype.Timestamptz `db:"created_at"`
	UpdatedAt          pgtype.Timestamptz `db:"updated_at"`
}

type TopicEvent struct {
	ID                 int32              `db:"id"`
	UserID             int32              `db:"user_id"`
	TopicID            int32              `db:"topic_id"`
	TimeTrackedSeconds int32              `db:"time_tracked_seconds"`
	Date               pgtype.Timestamptz `db:"date"`
}

type User struct {
	ID                 int32              `db:"id"`
	Email              string             `db:"email"`
	Username           string             `db:"username"`
	Password           string             `db:"password"`
	TimeTrackedSeconds int32              `db:"time_tracked_seconds"`
	CreatedAt          pgtype.Timestamptz `db:"created_at"`
	UpdatedAt          pgtype.Timestamptz `db:"updated_at"`
}
