// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: session.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createSession = `-- name: CreateSession :exec
INSERT INTO sessions(name, owner_id, max_participants, password, expires_at, topic)
VALUES($1, $2, $3, $4, $5, $6)
`

type CreateSessionParams struct {
	Name            string
	OwnerID         uuid.UUID
	MaxParticipants pgtype.Int4
	Password        pgtype.Text
	ExpiresAt       pgtype.Timestamptz
	Topic           pgtype.Text
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) error {
	_, err := q.db.Exec(ctx, createSession,
		arg.Name,
		arg.OwnerID,
		arg.MaxParticipants,
		arg.Password,
		arg.ExpiresAt,
		arg.Topic,
	)
	return err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions
WHERE id = $1
`

func (q *Queries) DeleteSession(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteSession, id)
	return err
}

const getSessionByNameAndOwnerID = `-- name: GetSessionByNameAndOwnerID :one
SELECT id, owner_id, name, max_participants, password, expires_at, topic, is_active, created_at, updated_at FROM sessions
WHERE name = $1 AND owner_id = $2
`

type GetSessionByNameAndOwnerIDParams struct {
	Name    string
	OwnerID uuid.UUID
}

func (q *Queries) GetSessionByNameAndOwnerID(ctx context.Context, arg GetSessionByNameAndOwnerIDParams) (Session, error) {
	row := q.db.QueryRow(ctx, getSessionByNameAndOwnerID, arg.Name, arg.OwnerID)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.MaxParticipants,
		&i.Password,
		&i.ExpiresAt,
		&i.Topic,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSessionByNameAndOwnerName = `-- name: GetSessionByNameAndOwnerName :one
SELECT sessions.id, sessions.owner_id, sessions.name, sessions.max_participants, sessions.password, sessions.expires_at, sessions.topic, sessions.is_active, sessions.created_at, sessions.updated_at FROM sessions
JOIN users ON users.id = sessions.owner_id
WHERE sessions.name = $1 AND users.username = $2
`

type GetSessionByNameAndOwnerNameParams struct {
	Name     string
	Username string
}

func (q *Queries) GetSessionByNameAndOwnerName(ctx context.Context, arg GetSessionByNameAndOwnerNameParams) (Session, error) {
	row := q.db.QueryRow(ctx, getSessionByNameAndOwnerName, arg.Name, arg.Username)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.MaxParticipants,
		&i.Password,
		&i.ExpiresAt,
		&i.Topic,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSessionParticipants = `-- name: GetSessionParticipants :many
SELECT id, user_id, session_id, last_seen_at, total_time_tracked_seconds, today_time_tracked_seconds FROM session_participants
WHERE session_id = $1
`

func (q *Queries) GetSessionParticipants(ctx context.Context, sessionID uuid.UUID) ([]SessionParticipant, error) {
	rows, err := q.db.Query(ctx, getSessionParticipants, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SessionParticipant{}
	for rows.Next() {
		var i SessionParticipant
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.SessionID,
			&i.LastSeenAt,
			&i.TotalTimeTrackedSeconds,
			&i.TodayTimeTrackedSeconds,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const joinSession = `-- name: JoinSession :exec
INSERT INTO session_participants(user_id, session_id, last_seen_at)
VALUES($1, $2, $3)
`

type JoinSessionParams struct {
	UserID     uuid.UUID
	SessionID  uuid.UUID
	LastSeenAt time.Time
}

func (q *Queries) JoinSession(ctx context.Context, arg JoinSessionParams) error {
	_, err := q.db.Exec(ctx, joinSession, arg.UserID, arg.SessionID, arg.LastSeenAt)
	return err
}

const updateSession = `-- name: UpdateSession :exec
UPDATE sessions
SET name = $2, max_participants = $3, password = $4, expires_at = $5, updated_at = now()
WHERE id = $1
`

type UpdateSessionParams struct {
	ID              uuid.UUID
	Name            string
	MaxParticipants pgtype.Int4
	Password        pgtype.Text
	ExpiresAt       pgtype.Timestamptz
}

func (q *Queries) UpdateSession(ctx context.Context, arg UpdateSessionParams) error {
	_, err := q.db.Exec(ctx, updateSession,
		arg.ID,
		arg.Name,
		arg.MaxParticipants,
		arg.Password,
		arg.ExpiresAt,
	)
	return err
}
