// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: session.sql

package query

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createSession = `-- name: CreateSession :exec
INSERT INTO sessions(name, owner_id, max_participants, expires_at, topic)
VALUES($1, $2, $3, $4, $5)
`

type CreateSessionParams struct {
	Name            string
	OwnerID         uuid.UUID
	MaxParticipants pgtype.Int4
	ExpiresAt       pgtype.Timestamptz
	Topic           pgtype.Text
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) error {
	_, err := q.db.Exec(ctx, createSession,
		arg.Name,
		arg.OwnerID,
		arg.MaxParticipants,
		arg.ExpiresAt,
		arg.Topic,
	)
	return err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions
WHERE owner_id = $1 AND name = $2
`

type DeleteSessionParams struct {
	OwnerID uuid.UUID
	Name    string
}

func (q *Queries) DeleteSession(ctx context.Context, arg DeleteSessionParams) error {
	_, err := q.db.Exec(ctx, deleteSession, arg.OwnerID, arg.Name)
	return err
}

const getJoinedSessions = `-- name: GetJoinedSessions :many
SELECT sessions.id, sessions.owner_id, sessions.name, sessions.max_participants, sessions.expires_at, sessions.topic, sessions.total_time_tracked_seconds, sessions.is_active, sessions.created_at, sessions.updated_at FROM session_participants
JOIN sessions ON sessions.id = session_participants.session_id
WHERE user_id = $1
`

func (q *Queries) GetJoinedSessions(ctx context.Context, userID uuid.UUID) ([]Session, error) {
	rows, err := q.db.Query(ctx, getJoinedSessions, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Session{}
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Name,
			&i.MaxParticipants,
			&i.ExpiresAt,
			&i.Topic,
			&i.TotalTimeTrackedSeconds,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSessionByNameAndOwnerID = `-- name: GetSessionByNameAndOwnerID :one
SELECT id, owner_id, name, max_participants, expires_at, topic, total_time_tracked_seconds, is_active, created_at, updated_at FROM sessions
WHERE 
    name = $1 
    AND owner_id = $2
    AND users.hide_user = FALSE
`

type GetSessionByNameAndOwnerIDParams struct {
	Name    string
	OwnerID uuid.UUID
}

func (q *Queries) GetSessionByNameAndOwnerID(ctx context.Context, arg GetSessionByNameAndOwnerIDParams) (Session, error) {
	row := q.db.QueryRow(ctx, getSessionByNameAndOwnerID, arg.Name, arg.OwnerID)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.MaxParticipants,
		&i.ExpiresAt,
		&i.Topic,
		&i.TotalTimeTrackedSeconds,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSessionByNameAndOwnerName = `-- name: GetSessionByNameAndOwnerName :one
SELECT sessions.id, sessions.owner_id, sessions.name, sessions.max_participants, sessions.expires_at, sessions.topic, sessions.total_time_tracked_seconds, sessions.is_active, sessions.created_at, sessions.updated_at FROM sessions
JOIN users ON users.id = sessions.owner_id
WHERE 
    sessions.name = $1
    AND users.username_normalized = LOWER($2)
    AND users.hide_user = FALSE
`

type GetSessionByNameAndOwnerNameParams struct {
	Name          string
	OwnerUsername string
}

func (q *Queries) GetSessionByNameAndOwnerName(ctx context.Context, arg GetSessionByNameAndOwnerNameParams) (Session, error) {
	row := q.db.QueryRow(ctx, getSessionByNameAndOwnerName, arg.Name, arg.OwnerUsername)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.MaxParticipants,
		&i.ExpiresAt,
		&i.Topic,
		&i.TotalTimeTrackedSeconds,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSessionsAll = `-- name: GetSessionsAll :many
SELECT
    sessions.id, sessions.owner_id, sessions.name, sessions.max_participants, sessions.expires_at, sessions.topic, sessions.total_time_tracked_seconds, sessions.is_active, sessions.created_at, sessions.updated_at,
    users.username AS owner_username,
    users.id AS owner_id
FROM sessions
JOIN users ON sessions.owner_id = users.id
WHERE
    sessions.is_active = TRUE
    AND users.hide_user = FALSE
    AND (
        EXISTS (
            SELECT 1
            FROM friends
            WHERE
                friends.is_accepted = TRUE
                AND (
                    (friends.sender_id = $1 AND friends.recipient_id = sessions.owner_id)
                    OR
                    (friends.recipient_id = $1 AND friends.sender_id = sessions.owner_id)
                )
        )
        OR
        EXISTS (
            SELECT 1
            FROM session_participants
            WHERE
                session_participants.session_id = sessions.id
                AND session_participants.user_id = $1
        )
    )
`

type GetSessionsAllRow struct {
	ID                      uuid.UUID
	OwnerID                 uuid.UUID
	Name                    string
	MaxParticipants         pgtype.Int4
	ExpiresAt               pgtype.Timestamptz
	Topic                   pgtype.Text
	TotalTimeTrackedSeconds int32
	IsActive                bool
	CreatedAt               time.Time
	UpdatedAt               time.Time
	OwnerUsername           string
	OwnerID_2               uuid.UUID
}

func (q *Queries) GetSessionsAll(ctx context.Context, senderID uuid.UUID) ([]GetSessionsAllRow, error) {
	rows, err := q.db.Query(ctx, getSessionsAll, senderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetSessionsAllRow{}
	for rows.Next() {
		var i GetSessionsAllRow
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Name,
			&i.MaxParticipants,
			&i.ExpiresAt,
			&i.Topic,
			&i.TotalTimeTrackedSeconds,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.OwnerUsername,
			&i.OwnerID_2,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const trackSessionTime = `-- name: TrackSessionTime :exec
UPDATE sessions
SET total_time_tracked_seconds = total_time_tracked_seconds + $2
WHERE id = $1
`

type TrackSessionTimeParams struct {
	ID          uuid.UUID
	TimeTracked int32
}

func (q *Queries) TrackSessionTime(ctx context.Context, arg TrackSessionTimeParams) error {
	_, err := q.db.Exec(ctx, trackSessionTime, arg.ID, arg.TimeTracked)
	return err
}

const updateSession = `-- name: UpdateSession :exec
UPDATE sessions
SET name = COALESCE($5, name), max_participants = $3, expires_at = $4, updated_at = NOW()
WHERE owner_id = $1 AND name = $2
`

type UpdateSessionParams struct {
	OwnerID         uuid.UUID
	Name            string
	MaxParticipants pgtype.Int4
	ExpiresAt       pgtype.Timestamptz
	NewName         string
}

func (q *Queries) UpdateSession(ctx context.Context, arg UpdateSessionParams) error {
	_, err := q.db.Exec(ctx, updateSession,
		arg.OwnerID,
		arg.Name,
		arg.MaxParticipants,
		arg.ExpiresAt,
		arg.NewName,
	)
	return err
}
