// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: session_tokens.sql

package query

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createSessionToken = `-- name: CreateSessionToken :exec
INSERT INTO session_tokens(user_id, hash, expiry)
VALUES($1, $2, $3)
`

type CreateSessionTokenParams struct {
	UserID uuid.UUID
	Hash   string
	Expiry time.Time
}

func (q *Queries) CreateSessionToken(ctx context.Context, arg CreateSessionTokenParams) error {
	_, err := q.db.Exec(ctx, createSessionToken, arg.UserID, arg.Hash, arg.Expiry)
	return err
}

const deleteSessionToken = `-- name: DeleteSessionToken :exec
DELETE FROM session_tokens
WHERE id = $1
`

func (q *Queries) DeleteSessionToken(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteSessionToken, id)
	return err
}

const getSessionToken = `-- name: GetSessionToken :one
SELECT id, user_id, hash, expiry, created_at, updated_at, last_used_at FROM session_tokens
WHERE hash = $1 AND expiry > now()
`

func (q *Queries) GetSessionToken(ctx context.Context, hash string) (SessionToken, error) {
	row := q.db.QueryRow(ctx, getSessionToken, hash)
	var i SessionToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Hash,
		&i.Expiry,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastUsedAt,
	)
	return i, err
}
