// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: session_participants.sql

package query

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
	"uuid"
)

const deleteExpiredSessionParticipants = `-- name: DeleteExpiredSessionParticipants :exec
DELETE FROM session_participants
USING sessions
WHERE 
  session_participants.session_id = sessions.id
  AND (sessions.expires_at IS NOT NULL AND sessions.expires_at < NOW())
`

func (q *Queries) DeleteExpiredSessionParticipants(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredSessionParticipants)
	return err
}

const getSessionParticipants = `-- name: GetSessionParticipants :many
SELECT users.username, users.last_seen_at, session_participants.id, session_participants.user_id, session_participants.session_id, session_participants.total_time_tracked_seconds, session_participants.today_time_tracked_seconds
FROM session_participants
JOIN users ON session_participants.user_id = users.id
WHERE 
    session_id = $1
    AND users.hide_user = FALSE
ORDER BY session_participants.total_time_tracked_seconds DESC
`

type GetSessionParticipantsRow struct {
	Username                string
	LastSeenAt              time.Time
	ID                      uuid.UUID
	UserID                  uuid.UUID
	SessionID               uuid.UUID
	TotalTimeTrackedSeconds int32
	TodayTimeTrackedSeconds int32
}

func (q *Queries) GetSessionParticipants(ctx context.Context, sessionID uuid.UUID) ([]GetSessionParticipantsRow, error) {
	rows, err := q.db.Query(ctx, getSessionParticipants, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetSessionParticipantsRow{}
	for rows.Next() {
		var i GetSessionParticipantsRow
		if err := rows.Scan(
			&i.Username,
			&i.LastSeenAt,
			&i.ID,
			&i.UserID,
			&i.SessionID,
			&i.TotalTimeTrackedSeconds,
			&i.TodayTimeTrackedSeconds,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const joinSession = `-- name: JoinSession :one
INSERT INTO session_participants (user_id, session_id)
SELECT
    $1,
    sessions.id
FROM sessions
JOIN users ON users.id = sessions.owner_id
WHERE sessions.name = $2
    AND users.username_normalized = LOWER($3)
    AND users.hide_user = FALSE
    AND (
        sessions.expires_at IS NULL
        OR sessions.expires_at > NOW()
    )
    AND (
        sessions.max_participants IS NULL
        OR (
            SELECT COUNT(*)
            FROM session_participants
            WHERE session_id = sessions.id
        ) < sessions.max_participants
    )
RETURNING (
    SELECT topic
    FROM sessions
    WHERE sessions.id = session_participants.session_id
) AS topic
`

type JoinSessionParams struct {
	UserID        uuid.UUID
	SessionName   string
	OwnerUsername string
}

func (q *Queries) JoinSession(ctx context.Context, arg JoinSessionParams) (pgtype.Text, error) {
	row := q.db.QueryRow(ctx, joinSession, arg.UserID, arg.SessionName, arg.OwnerUsername)
	var topic pgtype.Text
	err := row.Scan(&topic)
	return topic, err
}

const kickFromSession = `-- name: KickFromSession :exec
DELETE FROM session_participants
USING users, sessions
WHERE
    session_participants.user_id = users.id
    AND session_participants.session_id = sessions.id
    AND sessions.owner_id = $1 
    AND sessions.name = $2
    AND users.username_normalized = LOWER($3)
`

type KickFromSessionParams struct {
	OwnerID             uuid.UUID
	Name                string
	ParticipantUsername string
}

func (q *Queries) KickFromSession(ctx context.Context, arg KickFromSessionParams) error {
	_, err := q.db.Exec(ctx, kickFromSession, arg.OwnerID, arg.Name, arg.ParticipantUsername)
	return err
}

const leaveSession = `-- name: LeaveSession :exec
DELETE FROM session_participants
WHERE (
    user_id = $1
    AND session_id = (
        SELECT sessions.id
        FROM sessions
        JOIN users ON users.id = sessions.owner_id
        WHERE 
          sessions.name = $2
          AND users.username_normalized = LOWER($3)
    )
)
`

type LeaveSessionParams struct {
	UserID        uuid.UUID
	Name          string
	OwnerUsername string
}

func (q *Queries) LeaveSession(ctx context.Context, arg LeaveSessionParams) error {
	_, err := q.db.Exec(ctx, leaveSession, arg.UserID, arg.Name, arg.OwnerUsername)
	return err
}

const resetSessionParticipantTimeTrackedToday = `-- name: ResetSessionParticipantTimeTrackedToday :exec
UPDATE session_participants
SET today_time_tracked_seconds = 0
`

func (q *Queries) ResetSessionParticipantTimeTrackedToday(ctx context.Context) error {
	_, err := q.db.Exec(ctx, resetSessionParticipantTimeTrackedToday)
	return err
}

const trackSessionParticipantTime = `-- name: TrackSessionParticipantTime :exec
UPDATE session_participants
SET
    total_time_tracked_seconds = total_time_tracked_seconds + $3,
    today_time_tracked_seconds = today_time_tracked_seconds + $3
WHERE user_id = $1 AND session_id = $2
`

type TrackSessionParticipantTimeParams struct {
	UserID      uuid.UUID
	SessionID   uuid.UUID
	TimeTracked int32
}

func (q *Queries) TrackSessionParticipantTime(ctx context.Context, arg TrackSessionParticipantTimeParams) error {
	_, err := q.db.Exec(ctx, trackSessionParticipantTime, arg.UserID, arg.SessionID, arg.TimeTracked)
	return err
}
