// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: session_participants.sql

package query

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const getSessionParticipants = `-- name: GetSessionParticipants :many
SELECT users.username, users.last_seen_at, session_participants.id, session_participants.user_id, session_participants.session_id, session_participants.total_time_tracked_seconds, session_participants.today_time_tracked_seconds
FROM session_participants
JOIN users ON session_participants.user_id = users.id
WHERE 
    session_id = $1
    AND users.hide_user = FALSE
ORDER BY session_participants.total_time_tracked_seconds DESC
`

type GetSessionParticipantsRow struct {
	Username                string
	LastSeenAt              time.Time
	ID                      uuid.UUID
	UserID                  uuid.UUID
	SessionID               uuid.UUID
	TotalTimeTrackedSeconds int32
	TodayTimeTrackedSeconds int32
}

func (q *Queries) GetSessionParticipants(ctx context.Context, sessionID uuid.UUID) ([]GetSessionParticipantsRow, error) {
	rows, err := q.db.Query(ctx, getSessionParticipants, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetSessionParticipantsRow{}
	for rows.Next() {
		var i GetSessionParticipantsRow
		if err := rows.Scan(
			&i.Username,
			&i.LastSeenAt,
			&i.ID,
			&i.UserID,
			&i.SessionID,
			&i.TotalTimeTrackedSeconds,
			&i.TodayTimeTrackedSeconds,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const joinSession = `-- name: JoinSession :exec
INSERT INTO session_participants(user_id, session_id)
VALUES($1, $2)
`

type JoinSessionParams struct {
	UserID    uuid.UUID
	SessionID uuid.UUID
}

func (q *Queries) JoinSession(ctx context.Context, arg JoinSessionParams) error {
	_, err := q.db.Exec(ctx, joinSession, arg.UserID, arg.SessionID)
	return err
}

const kickFromSession = `-- name: KickFromSession :exec
DELETE FROM session_participants
USING users, sessions
WHERE
    session_participants.user_id = users.id
    AND session_participants.session_id = sessions.id
    AND sessions.owner_id = $1 
    AND sessions.name = $2
    AND users.username_normalized = LOWER($3)
`

type KickFromSessionParams struct {
	OwnerID             uuid.UUID
	Name                string
	ParticipantUsername string
}

func (q *Queries) KickFromSession(ctx context.Context, arg KickFromSessionParams) error {
	_, err := q.db.Exec(ctx, kickFromSession, arg.OwnerID, arg.Name, arg.ParticipantUsername)
	return err
}

const resetSessionParticipantTimeTrackedToday = `-- name: ResetSessionParticipantTimeTrackedToday :exec
UPDATE session_participants
SET today_time_tracked_seconds = 0
`

func (q *Queries) ResetSessionParticipantTimeTrackedToday(ctx context.Context) error {
	_, err := q.db.Exec(ctx, resetSessionParticipantTimeTrackedToday)
	return err
}

const trackSessionParticipantTime = `-- name: TrackSessionParticipantTime :exec
UPDATE session_participants
SET
    total_time_tracked_seconds = total_time_tracked_seconds + $3,
    today_time_tracked_seconds = today_time_tracked_seconds + $3
WHERE user_id = $1 AND session_id = $2
`

type TrackSessionParticipantTimeParams struct {
	UserID      uuid.UUID
	SessionID   uuid.UUID
	TimeTracked int32
}

func (q *Queries) TrackSessionParticipantTime(ctx context.Context, arg TrackSessionParticipantTimeParams) error {
	_, err := q.db.Exec(ctx, trackSessionParticipantTime, arg.UserID, arg.SessionID, arg.TimeTracked)
	return err
}
