// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: session.sql

package query

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createSession = `-- name: CreateSession :exec
INSERT INTO sessions(name, owner_id, max_participants, password, expires_at, topic)
VALUES($1, $2, $3, $4, $5, $6)
`

type CreateSessionParams struct {
	Name            string
	OwnerID         uuid.UUID
	MaxParticipants pgtype.Int4
	Password        pgtype.Text
	ExpiresAt       pgtype.Timestamptz
	Topic           pgtype.Text
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) error {
	_, err := q.db.Exec(ctx, createSession,
		arg.Name,
		arg.OwnerID,
		arg.MaxParticipants,
		arg.Password,
		arg.ExpiresAt,
		arg.Topic,
	)
	return err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions
WHERE owner_id = $1 AND name = $2
`

type DeleteSessionParams struct {
	OwnerID uuid.UUID
	Name    string
}

func (q *Queries) DeleteSession(ctx context.Context, arg DeleteSessionParams) error {
	_, err := q.db.Exec(ctx, deleteSession, arg.OwnerID, arg.Name)
	return err
}

const getSessionByNameAndOwnerID = `-- name: GetSessionByNameAndOwnerID :one
SELECT id, owner_id, name, max_participants, password, expires_at, topic, total_time_seconds, is_active, created_at, updated_at FROM sessions
WHERE name = $1 AND owner_id = $2
`

type GetSessionByNameAndOwnerIDParams struct {
	Name    string
	OwnerID uuid.UUID
}

func (q *Queries) GetSessionByNameAndOwnerID(ctx context.Context, arg GetSessionByNameAndOwnerIDParams) (Session, error) {
	row := q.db.QueryRow(ctx, getSessionByNameAndOwnerID, arg.Name, arg.OwnerID)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.MaxParticipants,
		&i.Password,
		&i.ExpiresAt,
		&i.Topic,
		&i.TotalTimeSeconds,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSessionByNameAndOwnerName = `-- name: GetSessionByNameAndOwnerName :one
SELECT sessions.id, sessions.owner_id, sessions.name, sessions.max_participants, sessions.password, sessions.expires_at, sessions.topic, sessions.total_time_seconds, sessions.is_active, sessions.created_at, sessions.updated_at FROM sessions
JOIN users ON users.id = sessions.owner_id
WHERE sessions.name = $1 AND users.username = $2
`

type GetSessionByNameAndOwnerNameParams struct {
	Name     string
	Username string
}

func (q *Queries) GetSessionByNameAndOwnerName(ctx context.Context, arg GetSessionByNameAndOwnerNameParams) (Session, error) {
	row := q.db.QueryRow(ctx, getSessionByNameAndOwnerName, arg.Name, arg.Username)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.MaxParticipants,
		&i.Password,
		&i.ExpiresAt,
		&i.Topic,
		&i.TotalTimeSeconds,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSessionParticipantsAsUsers = `-- name: GetSessionParticipantsAsUsers :many
SELECT session_participants.id, user_id, session_id, last_seen_at, session_participants.total_time_tracked_seconds, session_participants.today_time_tracked_seconds, users.id, email, username, password, users.total_time_tracked_seconds, users.today_time_tracked_seconds, country, hide_country, hide_user, created_at, updated_at FROM session_participants
JOIN users ON session_participants.user_id = users.id
WHERE session_id = $1
`

type GetSessionParticipantsAsUsersRow struct {
	ID                        uuid.UUID
	UserID                    uuid.UUID
	SessionID                 uuid.UUID
	LastSeenAt                time.Time
	TotalTimeTrackedSeconds   int32
	TodayTimeTrackedSeconds   int32
	ID_2                      uuid.UUID
	Email                     string
	Username                  string
	Password                  string
	TotalTimeTrackedSeconds_2 int32
	TodayTimeTrackedSeconds_2 int32
	Country                   pgtype.Text
	HideCountry               bool
	HideUser                  bool
	CreatedAt                 pgtype.Timestamptz
	UpdatedAt                 pgtype.Timestamptz
}

func (q *Queries) GetSessionParticipantsAsUsers(ctx context.Context, sessionID uuid.UUID) ([]GetSessionParticipantsAsUsersRow, error) {
	rows, err := q.db.Query(ctx, getSessionParticipantsAsUsers, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetSessionParticipantsAsUsersRow{}
	for rows.Next() {
		var i GetSessionParticipantsAsUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.SessionID,
			&i.LastSeenAt,
			&i.TotalTimeTrackedSeconds,
			&i.TodayTimeTrackedSeconds,
			&i.ID_2,
			&i.Email,
			&i.Username,
			&i.Password,
			&i.TotalTimeTrackedSeconds_2,
			&i.TodayTimeTrackedSeconds_2,
			&i.Country,
			&i.HideCountry,
			&i.HideUser,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSessionsAllByFriends = `-- name: GetSessionsAllByFriends :many
WITH friend_users AS (
    SELECT
        CASE
            WHEN sender_id = $1 THEN recipient_id
            ELSE sender_id
        END
    AS friend_id
    FROM friends
    WHERE
        (sender_id = $1 OR recipient_id = $1)
        AND is_accepted = TRUE
)
SELECT 
    sessions.id, sessions.owner_id, sessions.name, sessions.max_participants, sessions.password, sessions.expires_at, sessions.topic, sessions.total_time_seconds, sessions.is_active, sessions.created_at, sessions.updated_at,
    users.username AS owner_username,
    users.id AS owner_id
FROM sessions
JOIN friend_users ON sessions.owner_id = friend_users.friend_id
JOIN users ON sessions.owner_id = users.id
WHERE sessions.is_active = TRUE
`

type GetSessionsAllByFriendsRow struct {
	ID               uuid.UUID
	OwnerID          uuid.UUID
	Name             string
	MaxParticipants  pgtype.Int4
	Password         pgtype.Text
	ExpiresAt        pgtype.Timestamptz
	Topic            pgtype.Text
	TotalTimeSeconds int32
	IsActive         bool
	CreatedAt        time.Time
	UpdatedAt        time.Time
	OwnerUsername    string
	OwnerID_2        uuid.UUID
}

func (q *Queries) GetSessionsAllByFriends(ctx context.Context, senderID uuid.UUID) ([]GetSessionsAllByFriendsRow, error) {
	rows, err := q.db.Query(ctx, getSessionsAllByFriends, senderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetSessionsAllByFriendsRow{}
	for rows.Next() {
		var i GetSessionsAllByFriendsRow
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Name,
			&i.MaxParticipants,
			&i.Password,
			&i.ExpiresAt,
			&i.Topic,
			&i.TotalTimeSeconds,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.OwnerUsername,
			&i.OwnerID_2,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const joinSession = `-- name: JoinSession :exec
INSERT INTO session_participants(user_id, session_id, last_seen_at)
VALUES($1, $2, $3)
`

type JoinSessionParams struct {
	UserID     uuid.UUID
	SessionID  uuid.UUID
	LastSeenAt time.Time
}

func (q *Queries) JoinSession(ctx context.Context, arg JoinSessionParams) error {
	_, err := q.db.Exec(ctx, joinSession, arg.UserID, arg.SessionID, arg.LastSeenAt)
	return err
}

const kickFromSession = `-- name: KickFromSession :exec
DELETE FROM session_participants
USING users, sessions
WHERE
    session_participants.user_id = users.id
    AND session_participants.session_id = sessions.id
    AND sessions.owner_id = $1 
    AND sessions.name = $2
    AND users.username = $3
`

type KickFromSessionParams struct {
	OwnerID             uuid.UUID
	Name                string
	ParticipantUsername string
}

func (q *Queries) KickFromSession(ctx context.Context, arg KickFromSessionParams) error {
	_, err := q.db.Exec(ctx, kickFromSession, arg.OwnerID, arg.Name, arg.ParticipantUsername)
	return err
}

const updateSession = `-- name: UpdateSession :exec
UPDATE sessions
SET name = $2, max_participants = $3, password = $4, expires_at = $5, updated_at = now()
WHERE id = $1
`

type UpdateSessionParams struct {
	ID              uuid.UUID
	Name            string
	MaxParticipants pgtype.Int4
	Password        pgtype.Text
	ExpiresAt       pgtype.Timestamptz
}

func (q *Queries) UpdateSession(ctx context.Context, arg UpdateSessionParams) error {
	_, err := q.db.Exec(ctx, updateSession,
		arg.ID,
		arg.Name,
		arg.MaxParticipants,
		arg.Password,
		arg.ExpiresAt,
	)
	return err
}
