// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: token.sql

package query

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createOTPToken = `-- name: CreateOTPToken :exec
INSERT INTO otp_tokens(user_id, hash, expiry)
VALUES($1, $2, $3)
`

type CreateOTPTokenParams struct {
	UserID uuid.UUID
	Hash   string
	Expiry time.Time
}

func (q *Queries) CreateOTPToken(ctx context.Context, arg CreateOTPTokenParams) error {
	_, err := q.db.Exec(ctx, createOTPToken, arg.UserID, arg.Hash, arg.Expiry)
	return err
}

const createSessionToken = `-- name: CreateSessionToken :exec
INSERT INTO session_tokens(user_id, hash, expiry)
VALUES($1, $2, $3)
`

type CreateSessionTokenParams struct {
	UserID uuid.UUID
	Hash   string
	Expiry time.Time
}

func (q *Queries) CreateSessionToken(ctx context.Context, arg CreateSessionTokenParams) error {
	_, err := q.db.Exec(ctx, createSessionToken, arg.UserID, arg.Hash, arg.Expiry)
	return err
}

const deleteOTPToken = `-- name: DeleteOTPToken :exec
DELETE FROM otp_tokens
WHERE id = $1
`

func (q *Queries) DeleteOTPToken(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteOTPToken, id)
	return err
}

const deleteSessionToken = `-- name: DeleteSessionToken :exec
DELETE FROM session_tokens
WHERE id = $1
`

func (q *Queries) DeleteSessionToken(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteSessionToken, id)
	return err
}

const deleteSessionTokensOfUser = `-- name: DeleteSessionTokensOfUser :exec
DELETE FROM session_tokens
WHERE user_id = $1
`

func (q *Queries) DeleteSessionTokensOfUser(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteSessionTokensOfUser, userID)
	return err
}

const getOTPToken = `-- name: GetOTPToken :one
SELECT id, user_id, hash, expiry, created_at FROM otp_tokens
WHERE hash = $1 AND expiry > now()
`

func (q *Queries) GetOTPToken(ctx context.Context, hash string) (OtpToken, error) {
	row := q.db.QueryRow(ctx, getOTPToken, hash)
	var i OtpToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Hash,
		&i.Expiry,
		&i.CreatedAt,
	)
	return i, err
}

const getSessionToken = `-- name: GetSessionToken :one
SELECT id, user_id, hash, expiry, created_at, updated_at, last_used_at FROM session_tokens
WHERE hash = $1 AND expiry > now()
`

func (q *Queries) GetSessionToken(ctx context.Context, hash string) (SessionToken, error) {
	row := q.db.QueryRow(ctx, getSessionToken, hash)
	var i SessionToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Hash,
		&i.Expiry,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastUsedAt,
	)
	return i, err
}
