// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: topic.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createTopic = `-- name: CreateTopic :exec
INSERT INTO topics(name, created_by_user_id)
VALUES($1, $2)
`

type CreateTopicParams struct {
	Name            string
	CreatedByUserID uuid.UUID
}

func (q *Queries) CreateTopic(ctx context.Context, arg CreateTopicParams) error {
	_, err := q.db.Exec(ctx, createTopic, arg.Name, arg.CreatedByUserID)
	return err
}

const deleteTopic = `-- name: DeleteTopic :exec
DELETE FROM topics
WHERE id = $1
`

func (q *Queries) DeleteTopic(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteTopic, id)
	return err
}

const getAllTopics = `-- name: GetAllTopics :many
SELECT id, name, streak, today_time_tracked_seconds, total_time_tracked_seconds, created_by_user_id, created_at, updated_at FROM topics
`

func (q *Queries) GetAllTopics(ctx context.Context) ([]Topic, error) {
	rows, err := q.db.Query(ctx, getAllTopics)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Topic{}
	for rows.Next() {
		var i Topic
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Streak,
			&i.TodayTimeTrackedSeconds,
			&i.TotalTimeTrackedSeconds,
			&i.CreatedByUserID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTopicByID = `-- name: GetTopicByID :one
SELECT id, name, streak, today_time_tracked_seconds, total_time_tracked_seconds, created_by_user_id, created_at, updated_at FROM topics
WHERE id = $1
`

func (q *Queries) GetTopicByID(ctx context.Context, id uuid.UUID) (Topic, error) {
	row := q.db.QueryRow(ctx, getTopicByID, id)
	var i Topic
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Streak,
		&i.TodayTimeTrackedSeconds,
		&i.TotalTimeTrackedSeconds,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTopicOfUserByName = `-- name: GetTopicOfUserByName :one
SELECT id, name, streak, today_time_tracked_seconds, total_time_tracked_seconds, created_by_user_id, created_at, updated_at FROM topics
WHERE name = $1 AND created_by_user_id = $2
`

type GetTopicOfUserByNameParams struct {
	Name            string
	CreatedByUserID uuid.UUID
}

func (q *Queries) GetTopicOfUserByName(ctx context.Context, arg GetTopicOfUserByNameParams) (Topic, error) {
	row := q.db.QueryRow(ctx, getTopicOfUserByName, arg.Name, arg.CreatedByUserID)
	var i Topic
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Streak,
		&i.TodayTimeTrackedSeconds,
		&i.TotalTimeTrackedSeconds,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const increaseStreak = `-- name: IncreaseStreak :exec
UPDATE topics
SET streak = streak + 1
WHERE id = $1
`

func (q *Queries) IncreaseStreak(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, increaseStreak, id)
	return err
}

const loseStreak = `-- name: LoseStreak :exec
UPDATE topics
SET streak = 0
WHERE id = $1
`

func (q *Queries) LoseStreak(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, loseStreak, id)
	return err
}

const resetTopicTimeTrackedToday = `-- name: ResetTopicTimeTrackedToday :exec
UPDATE topics
SET today_time_tracked_seconds = 0
`

func (q *Queries) ResetTopicTimeTrackedToday(ctx context.Context) error {
	_, err := q.db.Exec(ctx, resetTopicTimeTrackedToday)
	return err
}

const trackTopicTime = `-- name: TrackTopicTime :exec
UPDATE topics
SET 
    total_time_tracked_seconds = total_time_tracked_seconds + $3,
    today_time_tracked_seconds = today_time_tracked_seconds + $3
WHERE id = $1 AND created_by_user_id = $2
`

type TrackTopicTimeParams struct {
	ID              uuid.UUID
	CreatedByUserID uuid.UUID
	TimeTracked     int32
}

func (q *Queries) TrackTopicTime(ctx context.Context, arg TrackTopicTimeParams) error {
	_, err := q.db.Exec(ctx, trackTopicTime, arg.ID, arg.CreatedByUserID, arg.TimeTracked)
	return err
}

const updateTopic = `-- name: UpdateTopic :exec
UPDATE topics
SET name = $2, total_time_tracked_seconds = $3, updated_at = now()
WHERE id = $1
`

type UpdateTopicParams struct {
	ID                      uuid.UUID
	Name                    string
	TotalTimeTrackedSeconds int32
}

func (q *Queries) UpdateTopic(ctx context.Context, arg UpdateTopicParams) error {
	_, err := q.db.Exec(ctx, updateTopic, arg.ID, arg.Name, arg.TotalTimeTrackedSeconds)
	return err
}
