// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: topic.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createTopic = `-- name: CreateTopic :exec
INSERT INTO topics(name, owner_id)
VALUES($1, $2)
`

type CreateTopicParams struct {
	Name    string
	OwnerID uuid.UUID
}

func (q *Queries) CreateTopic(ctx context.Context, arg CreateTopicParams) error {
	_, err := q.db.Exec(ctx, createTopic, arg.Name, arg.OwnerID)
	return err
}

const deleteTopic = `-- name: DeleteTopic :exec
DELETE FROM topics
WHERE id = $1
`

func (q *Queries) DeleteTopic(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteTopic, id)
	return err
}

const getTopicByID = `-- name: GetTopicByID :one
SELECT id, name, streak, today_time_tracked_seconds, total_time_tracked_seconds, owner_id, created_at, updated_at FROM topics
WHERE id = $1
`

func (q *Queries) GetTopicByID(ctx context.Context, id uuid.UUID) (Topic, error) {
	row := q.db.QueryRow(ctx, getTopicByID, id)
	var i Topic
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Streak,
		&i.TodayTimeTrackedSeconds,
		&i.TotalTimeTrackedSeconds,
		&i.OwnerID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTopicByOwner = `-- name: GetTopicByOwner :many
SELECT id, name, streak, today_time_tracked_seconds, total_time_tracked_seconds, owner_id, created_at, updated_at FROM topics
WHERE owner_id = $1
`

func (q *Queries) GetTopicByOwner(ctx context.Context, ownerID uuid.UUID) ([]Topic, error) {
	rows, err := q.db.Query(ctx, getTopicByOwner, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Topic{}
	for rows.Next() {
		var i Topic
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Streak,
			&i.TodayTimeTrackedSeconds,
			&i.TotalTimeTrackedSeconds,
			&i.OwnerID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTopicByOwnerAndName = `-- name: GetTopicByOwnerAndName :one
SELECT id, name, streak, today_time_tracked_seconds, total_time_tracked_seconds, owner_id, created_at, updated_at FROM topics
WHERE name = $1 AND owner_id = $2
`

type GetTopicByOwnerAndNameParams struct {
	Name    string
	OwnerID uuid.UUID
}

func (q *Queries) GetTopicByOwnerAndName(ctx context.Context, arg GetTopicByOwnerAndNameParams) (Topic, error) {
	row := q.db.QueryRow(ctx, getTopicByOwnerAndName, arg.Name, arg.OwnerID)
	var i Topic
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Streak,
		&i.TodayTimeTrackedSeconds,
		&i.TotalTimeTrackedSeconds,
		&i.OwnerID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTopicsAll = `-- name: GetTopicsAll :many
SELECT id, name, streak, today_time_tracked_seconds, total_time_tracked_seconds, owner_id, created_at, updated_at FROM topics
`

func (q *Queries) GetTopicsAll(ctx context.Context) ([]Topic, error) {
	rows, err := q.db.Query(ctx, getTopicsAll)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Topic{}
	for rows.Next() {
		var i Topic
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Streak,
			&i.TodayTimeTrackedSeconds,
			&i.TotalTimeTrackedSeconds,
			&i.OwnerID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const increaseStreak = `-- name: IncreaseStreak :exec
UPDATE topics
SET streak = streak + 1
WHERE id = $1
`

func (q *Queries) IncreaseStreak(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, increaseStreak, id)
	return err
}

const loseStreak = `-- name: LoseStreak :exec
UPDATE topics
SET streak = 0
WHERE id = $1
`

func (q *Queries) LoseStreak(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, loseStreak, id)
	return err
}

const resetTopicTimeTrackedToday = `-- name: ResetTopicTimeTrackedToday :exec
UPDATE topics
SET today_time_tracked_seconds = 0
`

func (q *Queries) ResetTopicTimeTrackedToday(ctx context.Context) error {
	_, err := q.db.Exec(ctx, resetTopicTimeTrackedToday)
	return err
}

const trackTopicTime = `-- name: TrackTopicTime :exec
UPDATE topics
SET 
    total_time_tracked_seconds = total_time_tracked_seconds + $3,
    today_time_tracked_seconds = today_time_tracked_seconds + $3
WHERE id = $1 AND owner_id = $2
`

type TrackTopicTimeParams struct {
	ID          uuid.UUID
	OwnerID     uuid.UUID
	TimeTracked int32
}

func (q *Queries) TrackTopicTime(ctx context.Context, arg TrackTopicTimeParams) error {
	_, err := q.db.Exec(ctx, trackTopicTime, arg.ID, arg.OwnerID, arg.TimeTracked)
	return err
}

const updateTopic = `-- name: UpdateTopic :exec
UPDATE topics
SET name = $2, updated_at = now()
WHERE id = $1
`

type UpdateTopicParams struct {
	ID   uuid.UUID
	Name string
}

func (q *Queries) UpdateTopic(ctx context.Context, arg UpdateTopicParams) error {
	_, err := q.db.Exec(ctx, updateTopic, arg.ID, arg.Name)
	return err
}
