// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: topic_event.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createTopicEvent = `-- name: CreateTopicEvent :exec
INSERT INTO topic_events(user_id, topic_id, time_tracked_seconds, date)
VALUES($1, $2, $3, $4)
`

type CreateTopicEventParams struct {
	UserID             uuid.UUID
	TopicID            uuid.UUID
	TimeTrackedSeconds int32
	Date               time.Time
}

func (q *Queries) CreateTopicEvent(ctx context.Context, arg CreateTopicEventParams) error {
	_, err := q.db.Exec(ctx, createTopicEvent,
		arg.UserID,
		arg.TopicID,
		arg.TimeTrackedSeconds,
		arg.Date,
	)
	return err
}

const deleteTopicEvent = `-- name: DeleteTopicEvent :exec
DELETE FROM topic_events
WHERE id = $1
`

func (q *Queries) DeleteTopicEvent(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteTopicEvent, id)
	return err
}

const getAllTopicEvents = `-- name: GetAllTopicEvents :many
SELECT id, user_id, topic_id, time_tracked_seconds, date FROM topic_events
WHERE user_id = $1
`

func (q *Queries) GetAllTopicEvents(ctx context.Context, userID uuid.UUID) ([]TopicEvent, error) {
	rows, err := q.db.Query(ctx, getAllTopicEvents, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TopicEvent{}
	for rows.Next() {
		var i TopicEvent
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.TopicID,
			&i.TimeTrackedSeconds,
			&i.Date,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTopicEventsToday = `-- name: GetTopicEventsToday :many
SELECT id, user_id, topic_id, time_tracked_seconds, date FROM topic_events
WHERE user_id = $1 AND DATE(date) = CURRENT_DATE
`

func (q *Queries) GetTopicEventsToday(ctx context.Context, userID uuid.UUID) ([]TopicEvent, error) {
	rows, err := q.db.Query(ctx, getTopicEventsToday, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TopicEvent{}
	for rows.Next() {
		var i TopicEvent
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.TopicID,
			&i.TimeTrackedSeconds,
			&i.Date,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTopicEvent = `-- name: UpdateTopicEvent :exec
UPDATE topic_events
SET time_tracked_seconds = $2, date = $3
WHERE id = $1
`

type UpdateTopicEventParams struct {
	ID                 uuid.UUID
	TimeTrackedSeconds int32
	Date               time.Time
}

func (q *Queries) UpdateTopicEvent(ctx context.Context, arg UpdateTopicEventParams) error {
	_, err := q.db.Exec(ctx, updateTopicEvent, arg.ID, arg.TimeTrackedSeconds, arg.Date)
	return err
}
