// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user.sql

package query

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :exec
INSERT INTO users(email, username, password, country)
VALUES($1, $2, $3, $4)
`

type CreateUserParams struct {
	Email    string
	Username string
	Password string
	Country  pgtype.Text
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) error {
	_, err := q.db.Exec(ctx, createUser,
		arg.Email,
		arg.Username,
		arg.Password,
		arg.Country,
	)
	return err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users
WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteUser, id)
	return err
}

const getTopUsers = `-- name: GetTopUsers :many
SELECT id, email, username, password, total_time_tracked_seconds, today_time_tracked_seconds, country, hide_country, hide_user, last_seen_at, created_at, updated_at FROM users
WHERE 
    total_time_tracked_seconds < $1
    AND username ILIKE $3 || '%'
    AND users.hide_user = FALSE
ORDER BY total_time_tracked_seconds DESC
LIMIT $2
`

type GetTopUsersParams struct {
	TotalTimeTrackedSeconds int32
	Limit                   int32
	MatchName               pgtype.Text
}

func (q *Queries) GetTopUsers(ctx context.Context, arg GetTopUsersParams) ([]User, error) {
	rows, err := q.db.Query(ctx, getTopUsers, arg.TotalTimeTrackedSeconds, arg.Limit, arg.MatchName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Username,
			&i.Password,
			&i.TotalTimeTrackedSeconds,
			&i.TodayTimeTrackedSeconds,
			&i.Country,
			&i.HideCountry,
			&i.HideUser,
			&i.LastSeenAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTopUsersLocal = `-- name: GetTopUsersLocal :many
SELECT users.id, users.email, users.username, users.password, users.total_time_tracked_seconds, users.today_time_tracked_seconds, users.country, users.hide_country, users.hide_user, users.last_seen_at, users.created_at, users.updated_at FROM users
JOIN users AS target_user ON target_user.id = $1
WHERE 
    users.country = target_user.country
    AND users.total_time_tracked_seconds < $2
    AND username ILIKE $4 || '%'
    AND users.hide_country = FALSE
    AND users.hide_user = FALSE
ORDER BY users.total_time_tracked_seconds DESC
LIMIT $3
`

type GetTopUsersLocalParams struct {
	ID                      uuid.UUID
	TotalTimeTrackedSeconds int32
	Limit                   int32
	MatchName               pgtype.Text
}

func (q *Queries) GetTopUsersLocal(ctx context.Context, arg GetTopUsersLocalParams) ([]User, error) {
	rows, err := q.db.Query(ctx, getTopUsersLocal,
		arg.ID,
		arg.TotalTimeTrackedSeconds,
		arg.Limit,
		arg.MatchName,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Username,
			&i.Password,
			&i.TotalTimeTrackedSeconds,
			&i.TodayTimeTrackedSeconds,
			&i.Country,
			&i.HideCountry,
			&i.HideUser,
			&i.LastSeenAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, username, password, total_time_tracked_seconds, today_time_tracked_seconds, country, hide_country, hide_user, last_seen_at, created_at, updated_at FROM users
WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.Password,
		&i.TotalTimeTrackedSeconds,
		&i.TodayTimeTrackedSeconds,
		&i.Country,
		&i.HideCountry,
		&i.HideUser,
		&i.LastSeenAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, username, password, total_time_tracked_seconds, today_time_tracked_seconds, country, hide_country, hide_user, last_seen_at, created_at, updated_at FROM users
WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.Password,
		&i.TotalTimeTrackedSeconds,
		&i.TodayTimeTrackedSeconds,
		&i.Country,
		&i.HideCountry,
		&i.HideUser,
		&i.LastSeenAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, email, username, password, total_time_tracked_seconds, today_time_tracked_seconds, country, hide_country, hide_user, last_seen_at, created_at, updated_at FROM users
WHERE username = $1
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.Password,
		&i.TotalTimeTrackedSeconds,
		&i.TodayTimeTrackedSeconds,
		&i.Country,
		&i.HideCountry,
		&i.HideUser,
		&i.LastSeenAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const resetUserTimeTrackedToday = `-- name: ResetUserTimeTrackedToday :exec
UPDATE users
SET today_time_tracked_seconds = 0
`

func (q *Queries) ResetUserTimeTrackedToday(ctx context.Context) error {
	_, err := q.db.Exec(ctx, resetUserTimeTrackedToday)
	return err
}

const trackUserTime = `-- name: TrackUserTime :exec
UPDATE users
SET
    total_time_tracked_seconds = total_time_tracked_seconds + $2,
    today_time_tracked_seconds = today_time_tracked_seconds + $2
WHERE id = $1
`

type TrackUserTimeParams struct {
	ID          uuid.UUID
	TimeTracked int32
}

func (q *Queries) TrackUserTime(ctx context.Context, arg TrackUserTimeParams) error {
	_, err := q.db.Exec(ctx, trackUserTime, arg.ID, arg.TimeTracked)
	return err
}

const updateUser = `-- name: UpdateUser :exec
UPDATE users
SET username = COALESCE($2, username), password = $3, updated_at = now()
WHERE id = $1
`

type UpdateUserParams struct {
	ID       uuid.UUID
	Username string
	Password string
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) error {
	_, err := q.db.Exec(ctx, updateUser, arg.ID, arg.Username, arg.Password)
	return err
}
