// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user.sql

package db

import (
	"context"
)

const createUser = `-- name: CreateUser :exec
INSERT INTO users(email, username, password, time_tracked_seconds)
VALUES($1, $2, $3, $4)
`

type CreateUserParams struct {
	Email              string `db:"email"`
	Username           string `db:"username"`
	Password           string `db:"password"`
	TimeTrackedSeconds int32  `db:"time_tracked_seconds"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) error {
	_, err := q.db.Exec(ctx, createUser,
		arg.Email,
		arg.Username,
		arg.Password,
		arg.TimeTrackedSeconds,
	)
	return err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users
WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteUser, id)
	return err
}

const getTopUsers = `-- name: GetTopUsers :many
SELECT id, email, username, password, time_tracked_seconds, created_at, updated_at FROM users
WHERE time_tracked_seconds < $1 
ORDER BY time_tracked_seconds DESC
LIMIT $2
`

type GetTopUsersParams struct {
	TimeTrackedSeconds int32 `db:"time_tracked_seconds"`
	Limit              int32 `db:"limit"`
}

func (q *Queries) GetTopUsers(ctx context.Context, arg GetTopUsersParams) ([]User, error) {
	rows, err := q.db.Query(ctx, getTopUsers, arg.TimeTrackedSeconds, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Username,
			&i.Password,
			&i.TimeTrackedSeconds,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, username, password, time_tracked_seconds, created_at, updated_at FROM users
WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.Password,
		&i.TimeTrackedSeconds,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, username, password, time_tracked_seconds, created_at, updated_at FROM users
WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id int32) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.Password,
		&i.TimeTrackedSeconds,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, email, username, password, time_tracked_seconds, created_at, updated_at FROM users
WHERE username = $1
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.Password,
		&i.TimeTrackedSeconds,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const trackUserTime = `-- name: TrackUserTime :exec
UPDATE users
SET time_tracked_seconds = time_tracked_seconds + $2
WHERE id = $1
`

type TrackUserTimeParams struct {
	ID                 int32 `db:"id"`
	TimeTrackedSeconds int32 `db:"time_tracked_seconds"`
}

func (q *Queries) TrackUserTime(ctx context.Context, arg TrackUserTimeParams) error {
	_, err := q.db.Exec(ctx, trackUserTime, arg.ID, arg.TimeTrackedSeconds)
	return err
}

const updateUser = `-- name: UpdateUser :exec
UPDATE users
SET email = $2, username = $3, password = $4, updated_at = now()
WHERE id = $1
`

type UpdateUserParams struct {
	ID       int32  `db:"id"`
	Email    string `db:"email"`
	Username string `db:"username"`
	Password string `db:"password"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) error {
	_, err := q.db.Exec(ctx, updateUser,
		arg.ID,
		arg.Email,
		arg.Username,
		arg.Password,
	)
	return err
}
