apiVersion: batch/v1
kind: Job
metadata:
  name: migrate
spec:
  backoffLimit: 5
  template:
    spec:
      restartPolicy: OnFailure

      containers:
        - name: migrate
          image: deployments-postgres:latest
          imagePullPolicy: IfNotPresent

          env:
            - name: POSTGRES_HOST
              value: postgres
            - name: POSTGRES_PORT
              value: "5432"
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_USER
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_DB
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD

          command:
            - /usr/local/bin/migrate
