vmsingle:
  spec:
    retentionPeriod: "7d"
    resources:
      limits:
        memory: 5Gi
      requests:
        memory: 1Gi
    storage:
      resources:
        requests:
          storage: 20Gi

vlsingle:
  enabled: true
  spec:
    retentionPeriod: "7d"
    storage:
      resources:
        requests:
          storage: 10Gi

vlagent:
  enabled: true
  spec:
    k8sCollector:
      enabled: true

vtsingle:
  enabled: true
  spec:
    retentionPeriod: "7d"
    storage:
      resources:
        requests:
          storage: 10Gi

grafana:
  service:
    type: LoadBalancer
  plugins:
    - victoriametrics-logs-datasource
