http:
  middlewares:
    rateLimit:
      rateLimit:
        average: 100
        burst: 100
    latencyCheck:
      circuitBreaker:
        expression: "LatencyAtQuantileMS(95.0) > 500"
    limitBody:
      buffering:
        maxRequestBodyBytes: 10485760
