log:
  level: WARN
api:
  insecure: true
  dashboard: true
providers:
  docker:
    exposedByDefault: false
  file:
    filename: /etc/traefik/traefik_dynamic.yml
    watch: true
entryPoints:
  web:
    address: ":80"
    # http:
      # redirections:
        # entryPoint:
          # to: websecure
          # scheme: https
  websecure:
    address: ":443"
certificatesResolvers:
  cloudflare:
    acme:
      storage: /var/traefik.certs/cloudflare-acme.json
      caServer: 'https://acme-v02.api.letsencrypt.org/directory'
      keyType: EC256
      dnsChallenge:
        provider: cloudflare
        resolvers:
          - "8.8.8.8:53"
