services:
  postgres:
    image: postgres:17-alpine
    container_name: postgres
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_DB: $POSTGRES_DB
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    healthcheck:
      test: "pg_isready -U $POSTGRES_USER"
      interval: 1s
      retries: 5

  migrate:
    image: postgres:17-alpine
    container_name: migrate
    depends_on: 
      postgres:
        condition: service_healthy
    environment:
      POSTGRES_HOST: $POSTGRES_HOST
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PORT: $POSTGRES_PORT
      POSTGRES_DB: $POSTGRES_DB
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    volumes:
      - ../../sql/migrations:/srv/migrations
      - ../../scripts/migrate.sh:/srv/migrate.sh
    entrypoint: ["/srv/migrate.sh"]

  redis:
    image: redis:8.10-alpine
    container_name: redis
    environment:
      REDIS_PASSWORD: $REDIS_PASSWORD
    healthcheck:
      test: "redis-cli --raw incr ping" 
      interval: 1s
      retries: 5
    command: redis-server --appendonly yes  --requirepass "${REDIS_PASSWORD}"

  api:
    build:
      context: ../..
      dockerfile: deployments/Dockerfile.api
    container_name: api
    expose:
      - "${APP_PORT}"
    depends_on:
      migrate:
        condition: service_completed_successfully
      redis:
        condition: service_healthy
    volumes:
      - ../../:/srv
    command: make run
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.chrono-api.entrypoints=web"
      - "traefik.http.routers.chrono-api.rule=Host(`$DOMAIN`)"
      - "traefik.http.services.chrono-api.loadbalancer.server.port=$APP_PORT"
      - "traefik.http.routers.chrono-api.middlewares=rateLimit@file,limitBody@file"

  traefik:
    image: traefik:v3.6
    container_name: traefik
    environment:
      CF_DNS_API_TOKEN: $CF_DNS_API_TOKEN
    command: "--certificatesresolvers.cloudflare.acme.email=$CF_EMAIL"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - ../../configs/traefik.yml:/etc/traefik/traefik.yaml:ro
      - ../../configs/traefik_dynamic.yml:/etc/traefik/traefik_dynamic.yml:ro
      - ../../certs:/var/traefik.certs:rw
      - /var/run/docker.sock:/var/run/docker.sock
