services:
  postgres:
    image: postgres:17-alpine
    container_name: test-postgres
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_DB: $POSTGRES_DB
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    healthcheck:
      test: "sh -c 'pg_isready -U $POSTGRES_USER'"
      interval: 1s
      retries: 5

  migrate:
    image: postgres:17-alpine
    container_name: test-migrate
    depends_on: 
      postgres:
        condition: service_healthy
    environment:
      POSTGRES_HOST: $POSTGRES_HOST
      POSTGRES_PORT: $POSTGRES_PORT
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_DB: $POSTGRES_DB
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    volumes:
      - ../../sql/migrations:/srv/migrations
      - ../../scripts/migrate.sh:/srv/migrate.sh
    entrypoint: ["/srv/migrate.sh", "test"]

  redis:
    image: redis:8.10-alpine
    container_name: test-redis
    environment:
      REDIS_PASSWORD: $REDIS_PASSWORD
    healthcheck:
      test: "redis-cli --raw incr ping" 
      interval: 1s
      retries: 5
    command: redis-server --appendonly yes  --requirepass "${REDIS_PASSWORD}"

  api:
    build:
      context: ../..
      dockerfile: deployments/Dockerfile.api
    container_name: test-api
    depends_on:
      migrate:
        condition: service_completed_successfully
      redis:
        condition: service_healthy
    volumes:
      - ../../:/srv
    entrypoint: ["make", "test"]
